apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: thvome@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: heroes-bot-encrypt-secret
    solvers:
    - http01:
        ingress:
            class: azure/application-gateway