apiVersion: v1
kind: Service
metadata:
    name: "rootbot"
    labels:
        app: "rootbot"
spec:
    ports:
    - port: 3978
      targetPort: 3978
      protocol: TCP
      name: http
    selector:
        app: "rootbot"